type: m
 
manager:
  address: chris.japanwest.cloudapp.azure.com:14001
  # 这里换成manager所在的服务器的ip
  password: '1ddg23fbyj45cGTRER6'
  # 这部分的端口和密码需要跟上一步 manager 参数里的保持一致，以连接 type s 部分监听的 tcp 端口
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  macAccount:
    use: true
  group:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'chenzhitong12@qq.com'
    password: 'tuixpxamgunthhhi'
    host: 'smtp.qq.com'
    # 这部分的邮箱和密码是用于发送注册验证邮件，重置密码邮件
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8381'
    site: 'chris.japanwest.cloudapp.azure.com'
    # cdn: 'http://xxx.com' # 静态资源cdn地址，可省略
    # icon: 'icon.png' # 自定义首页图标，默认路径在 ~/.ssmgr 可省略
    # googleAnalytics: 'UA-xxxxxxxx-x' # Google Analytics ID，可省略
    # gcmSenderId: '456102641793' # gcmSenderId 、gcmAPIKey 这两个是Chrome推送用的
    # gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  webgui_telegram:
    # telegram 机器人的配置，可省略
    use: true
    token: '191374681:AAw6oaVPR4nnY7T4CtW78QX-Xy2Q5WD3wmZ'
  alipay:
    # 如果不使用支付宝，这段可以去掉
    use: false
    appid: 2015012108272442
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
  paypal:
    # 如果不使用paypal，这段可以去掉
    use: false
    mode: 'live' # sandbox or live
    client_id: 'At9xcGd1t5L6OrICKNnp2g9'
    client_secret: 'EP40s6pQAZmqp_G_nrU9kKY4XaZph'
 
db: 'webgui2.sqlite'